### ISSUE TITLE
Feature request: hererocks integration

### ISSUE THREAD

**Issue by drauschenbach** [yuin/gopher-lua#148]
I recently discovered that GopherLua has a stand-alone interpreter. Awesome!

I think it is worth investigating doing an integration with the [hererocks](https://github.com/mpeterv/hererocks) project.

Lua-based open source libraries use `hererocks` to perform Travis CI matrix builds.

For example, here is a snip from `.travis.yml` in my [lua-thrift](https://github.com/BixData/lua-thrift/blob/0.10.0/.travis.yml) project:

```yml
env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
```

This ensures that every commit and PR gets its build and unit tests validated against Lua 5.1 & 5.2, and LuaJIT 2.0 and 2.1.

I'd really love to see Travis CI validation against GopherLua as well, possibly through an entry such as this:

```yml
env:
  - LUA="gopherlua=5.1"
```

What would be required for this is:
1. For the GopherLua project to adopt tagging and semver -- and possibly being more explicit about being a 5.1 VM. E.g. tag/version = `5.1-23` (release #23 of 5.1) -- leaving the door open to future support of 5.2+.
2. Interact with the author of hererocks in order to determine how best to integrate.

GopherLua is fantastic, and I'd love to drive broader adoption.
